name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - name: Set up JDK 1.8
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Checking your code format
        run: csbt scalafmtCheckAll headerCheck test:headerCheck
      - name: Run compile
        run: csbt +compile +test testsJS/run testsJVM/run
